#services:
#
#  backend:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: backend
#    command: sh -c "python manage.py runserver 0.0.0.0:8000"
#    volumes:
#      - ./core:/usr/src/app
#    ports:
#      - "8000:8000"
##    environment:
##      - PGDB_NAME=postgres
##      - PGDB_USER=postgres
##      - PGDB_PASS=postgres
##      - PGDB_HOST=db
##      - PGDB_PORT=5432
#    env_file:
#      - ./envs/.env.dev
#    restart: always
#
#
#  redis:
#    container_name: redis
#    image: redis
#    restart: always
#    ports:
#      - "6379:6379"
#    command: redis-server --save 60 1 --loglevel warning
#
#  db:
#    container_name: db
#    image: postgis/postgis:15-3.3
#    volumes:
#      - ./postgres/data:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_DB=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#    restart: always
#
#  mongo:
#    container_name: mongo
#    image: mongo:latest
#    restart: always
#    volumes:
#      - ./mongodb/data:/data/db
#    ports:
#      - "27017:27017"
#    environment:
#      # **ایجاد کاربر ریشه در هنگام راه‌اندازی:**
#      - MONGO_INITDB_ROOT_USERNAME=mongouser2  # کاربر دلخواه
#      - MONGO_INITDB_ROOT_PASSWORD=mongopass2 # رمز عبور دلخواه
#
#
#
#
#  celery_worker:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    command: celery -A core worker -l info
#    volumes:
#      - ./core:/usr/src/app
#    env_file:
#      - ./envs/.env.dev
#    environment:
#      # **این خط جدید اضافه یا جایگزین می‌شود:**
#      - MONGO_URI=mongodb://mongouser2:mongopass2@mongo:27017/sedo_logs?authSource=admin
#    depends_on:
#      - redis
#      - backend
#      - mongo
#
#  worker:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    command: celery -A core beat -l info
#    volumes:
#      - ./core:/usr/src/app
#    env_file:
#      - ./envs/.env.dev
#    depends_on:
#      - redis
#      - backend
#
#
#
##  mongo:
##    container_name: mongo
##    image: mongo:latest
##    restart: always
##    volumes:
##      - ./mongodb/data:/data/db
##    ports:
##      - "27017:27017"
##    environment:
##      - MONGO_URI=mongodb://mongouser:mongopass@mongo:27017/admin?authSource=admin
###    environment:
###      MONGO_INITDB_ROOT_USERNAME: mongouser
###      MONGO_INITDB_ROOT_PASSWORD: mongopass
##


#services:
#
#  # db:
#  #   container_name: db
#  #   image: postgres:15-alpine
#  #   volumes:
#  #     - ./postgres/data_base_farm:/var/lib/postgresql/data_base_farm
#  #   ports:
#  #     - "5432:5432"
#  #   environment:
#  #     - POSTGRES_DB=postgres
#  #     - POSTGRES_USER=postgres
#  #     - POSTGRES_PASSWORD=postgres
#  #   restart: always
#  db:
#    container_name: db
#    image: postgis/postgis:15-3.3
#    volumes:
#      - ./postgres/data:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_DB=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#    restart: always
#
#  redis:
#    container_name: redis
#    image: redis
#    restart: always
#    ports:
#      - "6379:6379"
#    command: redis-server --save 60 1 --loglevel warning
#
#  backend:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: backend
#    command: sh -c "python manage.py runserver 0.0.0.0:8000"
#    volumes:
#      - ./core:/usr/src/app
#      - ./media:/usr/src/app/media
#    ports:
#      - "8000:8000"
#
#    env_file:
#      - ./envs/.env.dev
#
#    #    environment:
#    #      - SECRET_KEY=test
#    #      - DEBUG=True
#    #      - COMINGSOON=False
#    #      - SHOW_DEBUGGER_TOOLBAR=True
#
#    restart: always
#    # depends_on:
#    #    - redis
#  celery_worker:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    command: celery -A core worker -l info
#    volumes:
#      - ./core:/usr/src/app
#    env_file:
#      - ./envs/.env.dev
#    depends_on:
#      - redis
#      - backend
#
#  worker:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    command: celery -A core beat -l info
#    volumes:
#      - ./core:/usr/src/app
#    env_file:
#      - ./envs/.env.dev
#    depends_on:
#      - redis
#      - backend
#
#
#
#
##  websocket:
##    build:
##      context: .
##      dockerfile: dockerfiles/dev/Dockerfile
##    container_name: websocket
##    command: daphne -b 0.0.0.0 -p 8000 core.asgi:application
##    volumes:
##      - ./core:/usr/src/app
##      - ./media:/usr/src/app/media
##    env_file:
##      - ./envs/.env.dev
##    ports:
##      - "8001:8000"
##    depends_on:
##      - redis
##      - db
#
#
## MongoDB Service (جدید) 💾
#  mongo:
#    container_name: mongo
#    image: mongo:latest  # استفاده از آخرین ایمیج رسمی MongoDB
#    restart: always
#    volumes:
#      - ./mongodb/data:/data/db # ذخیره‌سازی داده‌های MongoDB در پوشه محلی mongodb/data
#    ports:
#      - "27017:27017" # پورت پیش‌فرض MongoDB
#    environment:
#      - MONGO_URI=mongodb://mongouser:mongopass@mongo:27017/admin?authSource=admin
#      # استفاده از متغیرهای محیطی برای تنظیمات اولیه (اختیاری، اما توصیه می‌شود)
##      - MONGO_INITDB_ROOT_USERNAME=mongouser
##      - MONGO_INITDB_ROOT_PASSWORD=mongopass
#
#
#
#volumes:
#  smtp4dev-data:

services:

  db:
    container_name: db
    image: postgis/postgis:15-3.3
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always

  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./core:/usr/src/app
      - ./media:/usr/src/app/media
    ports:
      - "8000:8000"
    env_file:
      - ./envs/.env.dev
    restart: always

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A core worker -l info
    volumes:
      - ./core:/usr/src/app
    env_file:
      - ./envs/.env.dev
    depends_on:
      - redis
      - backend

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A core beat -l info
    volumes:
      - ./core:/usr/src/app
    env_file:
      - ./envs/.env.dev
    depends_on:
      - redis
      - backend

# MongoDB Service (اصلاح شده)
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    volumes:
      - ./mongodb/data:/data/db
    ports:
      - "27017:27017"
    environment:
      # **Credential های جدید برای اطمینان از عدم استفاده توسط جای دیگر**
      - MONGO_INITDB_ROOT_USERNAME=mongouser
      - MONGO_INITDB_ROOT_PASSWORD=mongopass


volumes:
  smtp4dev-data: